CREATE DATABASE PRODUCTOS;
USE PRODUCTOS;

CREATE TABLE PRODUCTOS(
	id 	INT AUTO_INCREMENT	PRIMARY KEY,
	nombre VARCHAR(150) NOT NULL,
	imagen TEXT NULL,
	descripcion TEXT NOT NULL,
	precio DECIMAL(7,2) NOT NULL,
	descuento INT	NULL
)ENGINE=INNODB;

INSERT INTO PRODUCTOS VALUES
	(NULL, 
	'CABLE INALAMBRICO', 
	NULL, 
	'Es un super cable bien chevere', 
	20.99,
	10);